name: Windows-RDP
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Aktifkan RDP
      run: |
        net user runneradmin P@ssw0rd123
        netsh advfirewall firewall add rule name="Open RDP" dir=in action=allow protocol=TCP localport=3389
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Download SSH client (Plink dari PuTTY)
      run: |
        Invoke-WebRequest https://the.earth.li/~sgtatham/putty/latest/w64/plink.exe -OutFile "$env:USERPROFILE\plink.exe"

    - name: Jalankan Serveo tunnel ke RDP
      run: |
        Start-Process -NoNewWindow -FilePath "$env:USERPROFILE\plink.exe" -ArgumentList "-ssh -R 3389:localhost:3389 serveo.net -l serveo -batch"
        Start-Sleep -Seconds 15

    - name: Info login
      run: |
        echo "==============================="
        echo "Username: runneradmin"
        echo "Password: P@ssw0rd123"
        echo "Silakan cek di log atas alamat dari serveo (biasanya seperti 12345.serveo.net:3389)"
        echo "Gunakan alamat itu di Remote Desktop (RDP)"
        echo "==============================="
